export const TOGGLE_BOOKMARK = 'TOGGLE_BOOKMARK';
export const BOOKMARK_ERROR = 'BOOKMARK_ERROR';
export const SET_INITIAL_BOOKMARK_STATUS = 'SET_INITIAL_BOOKMARK_STATUS';
export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
