export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const COMMENT_ERROR = 'COMMENT_ERROR';
export const GET_COMMENTS = 'GET_COMMENTS';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const COMMENT_REQUEST = 'COMMENT_REQUEST';
