export const PASSWORD_RESET_START = 'PASSWORD_RESET_START ';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAILURE = 'PASSWORD_RESET_FAILURE';
export const TOKEN_RESET_FAILURE = 'TOKEN_RESET_FAILURE';
