export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_START = 'GET_ARTICLES_START';
export const GET_ARTICLES_ERROR = 'GET_ARTICLES_ERROR';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
